### ISSUE TITLE
Raspbian

### ISSUE THREAD

**Issue by tytot** [SalmonGER/PocketMine-MP-Binaries#8]
Do you have the 7.0.12 binaries for the Raspberry Pi by any chance? I need it for XBOX authentication on my server.
Thanks!

**Comment by SalmonGER** [comment]
I'll try to compile them. Looks good so far. But I need you to test them first. :)

**Comment by tytot** [comment]
Here's the error I get:
`start.sh: line 54: /home/pi/Desktop/PocketMine/bin/php7/bin/php: cannot execute binary file: Exec format error
`

**Comment by SalmonGER** [comment]
Could you try the x64 Linux binaries? @tytot
