### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by SuperXingKong** [SalmonGER/PocketMine-MP-Binaries#9]
many thanks for you.
and how to make a php binary for respberrypi?:

**Comment by SalmonGER** [comment]
I don't really really understand your question. Could you explain it to me more?

**Comment by SuperXingKong** [comment]
I want to know how to make these:)
Could you teach me?

**Comment by SalmonGER** [comment]
I use the php build scripts to make sure the extensions are installed properly. But basically you just need to know how to compile php with your custom configuration
